name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  event-data:
    description: 'information about github event'
    required: true
    default: ''
  github-api-token:
    description: 'github api token'
    required: true
    default: 'zzz'
  twitter-api-token:
    description: 'twitter api token'
    required: true
    default: 'yyy'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.event-data }}
    - ${{ inputs.github-api-token }}
    - ${{ inputs.twitter-api-token }}
